[build]
  base = "../"  # Base directory is one level up from the client folder
  command = "npm run build"
  publish = "todolist/client/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
