"""Add checked and is_new attribute to Task model

Revision ID: 74d72c4fa5f2
Revises: 
Create Date: 2024-05-24 11:56:05.121545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d72c4fa5f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_new', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_new')
        batch_op.drop_column('checked')

    # ### end Alembic commands ###
